// ============================================================
// PharmaWallah — Disk Diffusion Lab: the PDF lab report
// ============================================================
//
// Carried over from the original simulation and extended: the report now
// records the conditions the plate was run under (inoculum, agar depth, lawn
// coverage, incubation) and names the interpretive criteria used, because a
// susceptibility result without its conditions cannot be checked.
//
// jsPDF is already a project dependency; it is imported lazily so the ~350 KB
// only downloads when a student actually asks for a report.

import {
  ANTIBIOTIC_BY_ID,
  MIN_DISK_SPACING_MM,
} from "./data";
import { getInterpretationSystem, interpretZone } from "./engine";
import type { DiskPlacement, Measurement, Organism } from "./types";

export interface ReportInput {
  organism: Organism;
  placements: DiskPlacement[];
  measurements: Record<string, Measurement>;
  zones: Record<string, number>;
  interpretationSystemId: string;
  turbidity: string;
  agarDepth: string;
  coveragePercent: number;
  incubationTempC: number;
  incubationHours: number;
  techniquePercent: number;
  seed: string;
}

export async function generateReport(input: ReportInput): Promise<void> {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const system = getInterpretationSystem(input.interpretationSystemId);

  // Header — the brand band the original report used.
  doc.setFillColor(28, 123, 217);
  doc.rect(0, 0, W, 30, "F");
  doc.setFillColor(33, 182, 122);
  doc.rect(0, 27, W, 4, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(19);
  doc.setFont("helvetica", "bold");
  doc.text("PharmaWallah", 15, 15);
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.text("Virtual laboratory - disk diffusion susceptibility test", 15, 23);
  doc.text(new Date().toLocaleString("en-PK"), W - 15, 15, { align: "right" });

  // Simulation notice, first thing on the page so it cannot be mistaken for a
  // clinical report.
  doc.setFillColor(255, 247, 224);
  doc.roundedRect(15, 38, W - 30, 14, 2, 2, "F");
  doc.setTextColor(146, 64, 14);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.text(
    "SIMULATED RESULT - generated by an educational model. Not a clinical report and not from a real isolate.",
    W / 2,
    46.5,
    { align: "center" },
  );

  // Isolate and case
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Isolate", 15, 62);
  doc.setFontSize(10);
  doc.text(`${input.organism.name}  (${input.organism.strain})`, 15, 69);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(input.organism.morphology, 15, 75);
  const caseLines = doc.splitTextToSize(input.organism.caseStudy, W - 30);
  doc.text(caseLines, 15, 83);

  // Conditions
  let y = 83 + caseLines.length * 4.6 + 8;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Test conditions", 15, y);
  y += 7;
  doc.setFontSize(9);
  const conditions: [string, string][] = [
    ["Medium", "Mueller-Hinton agar"],
    ["Agar depth", input.agarDepth],
    ["Inoculum", input.turbidity],
    ["Lawn coverage", `${input.coveragePercent}% of the agar surface`],
    ["Incubation", `${input.incubationHours} h at ${input.incubationTempC} C, in air`],
    ["Disk spacing rule", `minimum ${MIN_DISK_SPACING_MM} mm centre to centre`],
    ["Criteria used", system.label],
    ["Experiment seed", input.seed],
  ];
  conditions.forEach(([k, v], i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = 15 + col * ((W - 30) / 2);
    doc.setFont("helvetica", "bold");
    doc.text(`${k}:`, x, y + row * 6);
    doc.setFont("helvetica", "normal");
    doc.text(v, x + 32, y + row * 6);
  });
  y += Math.ceil(conditions.length / 2) * 6 + 8;

  // Results table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Results", 15, y);
  y += 5;
  doc.setFillColor(241, 245, 249);
  doc.rect(15, y, W - 30, 8, "F");
  doc.setFontSize(7.5);
  doc.setTextColor(100, 116, 139);
  const cols = [18, 62, 95, 120, 152];
  ["Antibiotic", "Disk", "Diameter", "Criteria", "Report"].forEach((h, i) =>
    doc.text(h.toUpperCase(), cols[i], y + 5.5),
  );
  y += 13;

  doc.setFontSize(9);
  input.placements.forEach((p, i) => {
    const antibiotic = ANTIBIOTIC_BY_ID[p.antibioticId];
    const measurement = input.measurements[p.antibioticId];
    const diameter = measurement?.recorded ?? input.zones[p.antibioticId] ?? 0;
    const result = interpretZone(input.interpretationSystemId, p.antibioticId, input.organism, diameter);

    if (i % 2 === 0) {
      doc.setFillColor(249, 250, 251);
      doc.rect(15, y - 5, W - 30, 9, "F");
    }
    doc.setTextColor(30, 41, 59);
    doc.setFont("helvetica", "bold");
    doc.text(antibiotic?.name ?? p.antibioticId, cols[0], y);
    doc.setFont("helvetica", "normal");
    doc.text(antibiotic?.diskContent ?? "-", cols[1], y);
    doc.text(measurement ? `${diameter} mm` : "not measured", cols[2], y);
    doc.text(
      result.criteria ? `S >= ${result.criteria.susceptible} / R <= ${result.criteria.resistant}` : "none",
      cols[3],
      y,
    );
    const tone: [number, number, number] =
      result.category === "S"
        ? [22, 163, 74]
        : result.category === "R"
          ? [220, 38, 38]
          : result.category === "I"
            ? [217, 119, 6]
            : [100, 116, 139];
    doc.setTextColor(...tone);
    doc.setFont("helvetica", "bold");
    doc.text(result.category === "NI" ? "no criteria" : result.label, cols[4], y);
    y += 9;
  });

  // Criteria note — the thing that makes the numbers honest.
  y += 4;
  doc.setTextColor(30, 41, 59);
  doc.setFillColor(239, 246, 255);
  const noteLines = doc.splitTextToSize(system.sourceNote, W - 40);
  doc.roundedRect(15, y, W - 30, noteLines.length * 4.4 + 12, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.text("On these criteria", 20, y + 7);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(noteLines, 20, y + 13);

  // Footer
  doc.setFillColor(241, 245, 249);
  doc.rect(0, H - 20, W, 20, "F");
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text(`Technique score: ${input.techniquePercent}%`, 15, H - 12);
  doc.text("PharmaWallah - virtual pharmacy laboratory - educational use only", W / 2, H - 6, {
    align: "center",
  });

  doc.save(`PharmaWallah_DiskDiffusion_${input.organism.id}_${input.seed}.pdf`);
}
