// src/lib/courses/subjects/natural-toxins.ts
import { SubjectMeta } from "../types";

export const naturalToxinsSubject: SubjectMeta = {
  slug: "natural-toxins",
  semesterSlug: "sem-6",
  semester: "Semester 6",
  title: "Natural Toxins",
  subjectCode: "PHR-601",
  icon: "☠️",
  description: "Plant, fungal and animal toxins relevant to pharmacy practice.",
  gradient: "from-purple-600 to-pink-400",
  units: [
    {
      id: "unit1-intro-natural-toxins",
      title: "Introduction to Natural Toxins",
      shortTitle: "Introduction",
      description: "Classification and general principles of toxicology.",
      emoji: "☠️",
      gradient: "from-purple-600 to-pink-400",
      readTime: 12,
      difficulty: "Beginner",
      previewImage: "/previews/naturaltoxins/unit1-intro.jpg",
      contentFile: "natural-toxins/unit1-intro-natural-toxins.md",
    },
    {
      id: "unit2-higher-plant-toxins",
      title: "Higher Plant Toxins",
      shortTitle: "Higher Plant Toxins",
      description: "Toxic principles from higher plants.",
      emoji: "🌿",
      gradient: "from-purple-600 to-pink-400",
      readTime: 15,
      difficulty: "Intermediate",
      previewImage: "/previews/naturaltoxins/unit2-higher-plants.jpg",
      contentFile: "natural-toxins/unit2-higher-plant-toxins.md",
    },
    {
      id: "unit3-lower-plant-toxins",
      title: "Lower Plant Toxins",
      shortTitle: "Lower Plant Toxins",
      description: "Toxins from algae, fungi and lower plants.",
      emoji: "🍄",
      gradient: "from-purple-600 to-pink-400",
      readTime: 14,
      difficulty: "Intermediate",
      previewImage: "/previews/naturaltoxins/unit3-lower-plants.jpg",
      contentFile: "natural-toxins/unit3-lower-plant-toxins.md",
    },
    {
      id: "unit4-mycotoxins",
      title: "Mycotoxins",
      shortTitle: "Mycotoxins",
      description: "Fungal toxins and their pharmacological relevance.",
      emoji: "🧫",
      gradient: "from-purple-600 to-pink-400",
      readTime: 13,
      difficulty: "Intermediate",
      previewImage: "/previews/naturaltoxins/unit4-mycotoxins.jpg",
      contentFile: "natural-toxins/unit4-mycotoxins.md",
    },
    {
      id: "unit5-animal-toxins",
      title: "Animal Toxins",
      shortTitle: "Animal Toxins",
      description: "Venoms and toxins of animal origin.",
      emoji: "🐍",
      gradient: "from-purple-600 to-pink-400",
      readTime: 16,
      difficulty: "Advanced",
      previewImage: "/previews/naturaltoxins/unit5-animal-toxins.jpg",
      contentFile: "natural-toxins/unit5-animal-toxins.md",
    },
    {
      id: "unit6-prevention-control-toxins",
      title: "Prevention & Control of Toxins",
      shortTitle: "Prevention & Control",
      description: "Detection, prevention and management strategies.",
      emoji: "🛡️",
      gradient: "from-purple-600 to-pink-400",
      readTime: 15,
      difficulty: "Intermediate",
      previewImage: "/previews/naturaltoxins/unit6-prevention.jpg",
      contentFile: "natural-toxins/unit6-prevention-control-toxins.md",
    },
  ],
};