// src/lib/courses/subjects/physiology.ts
import type { SubjectMeta } from "../types";

export const physiologySubject: SubjectMeta = {
    slug: "physiology",
    semesterSlug: "sem-1",
    semester: "Semester 1",
    title: "Physiology",
    subjectCode: "PHYS-101",
    icon: "🫀",
    description:
        "Understand how the human body works – from cell functions to organ systems.",
    gradient: "from-red-600 to-pink-400",
    hasMcq: true,
    units: [
        {
            id: "unit1-basic-cell-functions",
            title: "Unit 1: Basic Cell Functions",
            shortTitle: "Basic Cell Functions",
            emoji: "🔬",
            description: "Cell structure, membrane transport, osmosis, cell cycle & apoptosis.",
            readTime: 12,
            difficulty: "Beginner",
            gradient: "from-blue-600 to-cyan-400",
            previewImage: "/previews/physio/Basi cell functions infographic.webp",
            contentFile: "physiology-histology-1/unit1-basic-cell-functions.md",
        },
        {
            id: "unit2-muscle-physiology",
            title: "Unit 2: Muscle Physiology",
            shortTitle: "Muscle Physiology",
            emoji: "💪",
            description: "Skeletal, smooth & cardiac muscle contraction mechanisms.",
            readTime: 14,
            difficulty: "Intermediate",
            gradient: "from-amber-500 to-orange-400",
            previewImage: "/previews/physio/unit2-muscle.webp",
            contentFile: "physiology-histology-1/unit2-muscle-physiology.md",
        },
        {
            id: "unit3-circulation",
            title: "Unit 3: Circulation",
            shortTitle: "Circulation",
            emoji: "🩸",
            description: "Blood flow, haemodynamics, and regulation of circulation.",
            readTime: 14,
            difficulty: "Intermediate",
            gradient: "from-red-500 to-pink-400",
            previewImage: "/previews/physio/unit3-circulation.webp",
            contentFile: "physiology-histology-1/unit3-circulation.md",
        },
        {
            id: "unit4-the-heart",
            title: "Unit 4: The Heart",
            shortTitle: "The Heart",
            emoji: "❤️",
            description: "Cardiac cycle, ECG, regulation of heart function.",
            readTime: 16,
            difficulty: "Advanced",
            gradient: "from-rose-500 to-pink-400",
            previewImage: "/previews/physio/unit4-heart.webp",
            contentFile: "physiology-histology-1/unit4-the-heart.md",
        },
        {
            id: "unit5-blood-cells",
            title: "Unit 5: The Blood Cells",
            shortTitle: "Blood Cells",
            emoji: "🅱️",
            description: "RBCs, WBCs, platelets, haemostasis & blood groups.",
            readTime: 15,
            difficulty: "Intermediate",
            gradient: "from-red-600 to-orange-400",
            previewImage: "/previews/physio/unit5-blood.webp",
            contentFile: "physiology-histology-1/unit5-blood-cells.md",
        },
        {
            id: "unit6-digestion-absorption",
            title: "Unit 6: Digestion and Absorption of Food",
            shortTitle: "Digestion & Absorption",
            emoji: "🍽️",
            description: "Gastrointestinal physiology, enzymes & nutrient uptake.",
            readTime: 16,
            difficulty: "Intermediate",
            gradient: "from-green-500 to-teal-400",
            previewImage: "/previews/physio/unit6-digestion.webp",
            contentFile: "physiology-histology-1/unit6-digestion-absorption.md",
        },
        {
            id: "unit7-temperature-regulation",
            title: "Unit 7: Temperature Regulation",
            shortTitle: "Temperature Regulation",
            emoji: "🌡️",
            description: "Thermoregulation, fever, and heat exchange mechanisms.",
            readTime: 12,
            difficulty: "Beginner",
            gradient: "from-violet-600 to-purple-400",
            previewImage: "/previews/physio/unit7-temp.webp",
            contentFile: "physiology-histology-1/unit7-temperature-regulation.md",
        },
    ],
};