/*
 * GENERATED by scripts/build-molecule-library.mts on 2026-09-16 — do not edit by hand.
 * Source: PubChem (identity, formula, weight, SMILES, MeSH Pharmacological
 * Classification). Structural categories are confirmed by the lab's own rules.
 */
import type { LibraryEntry } from "./library";

export const LIBRARY: LibraryEntry[] = [
  {
    "id": "water",
    "name": "Water",
    "cid": 962,
    "formula": "H2O",
    "mw": 18.015,
    "smiles": "O",
    "iupac": "oxidane",
    "categories": [
      "common"
    ],
    "mesh": []
  },
  {
    "id": "methane",
    "name": "Methane",
    "cid": 297,
    "formula": "CH4",
    "mw": 16.043,
    "smiles": "C",
    "iupac": "methane",
    "categories": [
      "common"
    ],
    "mesh": []
  },
  {
    "id": "ammonia",
    "name": "Ammonia",
    "cid": 222,
    "formula": "H3N",
    "mw": 17.031,
    "smiles": "N",
    "iupac": "azane",
    "categories": [
      "common"
    ],
    "mesh": []
  },
  {
    "id": "carbon-dioxide",
    "name": "Carbon Dioxide",
    "cid": 280,
    "formula": "CO2",
    "mw": 44.009,
    "smiles": "C(=O)=O",
    "iupac": "carbon dioxide",
    "categories": [
      "common"
    ],
    "mesh": []
  },
  {
    "id": "ethanol",
    "name": "Ethanol",
    "cid": 702,
    "formula": "C2H6O",
    "mw": 46.07,
    "smiles": "CCO",
    "iupac": "ethanol",
    "categories": [
      "common"
    ],
    "mesh": []
  },
  {
    "id": "acetic-acid",
    "name": "Acetic Acid",
    "cid": 176,
    "formula": "C2H4O2",
    "mw": 60.05,
    "smiles": "CC(=O)O",
    "iupac": "acetic acid",
    "categories": [
      "common"
    ],
    "mesh": []
  },
  {
    "id": "benzene",
    "name": "Benzene",
    "cid": 241,
    "formula": "C6H6",
    "mw": 78.11,
    "smiles": "C1=CC=CC=C1",
    "iupac": "benzene",
    "categories": [
      "common"
    ],
    "mesh": []
  },
  {
    "id": "urea",
    "name": "Urea",
    "cid": 1176,
    "formula": "CH4N2O",
    "mw": 60.056,
    "smiles": "C(=O)(N)N",
    "iupac": "urea",
    "categories": [
      "common"
    ],
    "mesh": []
  },
  {
    "id": "ethene-ethylene",
    "name": "Ethene (ethylene)",
    "cid": 6325,
    "formula": "C2H4",
    "mw": 28.05,
    "smiles": "C=C",
    "iupac": "ethene",
    "categories": [
      "common"
    ],
    "mesh": []
  },
  {
    "id": "ethyne-acetylene",
    "name": "Ethyne (acetylene)",
    "cid": 6326,
    "formula": "C2H2",
    "mw": 26.04,
    "smiles": "C#C",
    "iupac": "acetylene",
    "categories": [
      "common"
    ],
    "mesh": []
  },
  {
    "id": "glycerol",
    "name": "Glycerol",
    "cid": 753,
    "formula": "C3H8O3",
    "mw": 92.09,
    "smiles": "C(C(CO)O)O",
    "iupac": "propane-1,2,3-triol",
    "categories": [
      "common"
    ],
    "mesh": []
  },
  {
    "id": "methanol",
    "name": "Methanol",
    "cid": 887,
    "formula": "CH4O",
    "mw": 32.042,
    "smiles": "CO",
    "iupac": "methanol",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "phenol",
    "name": "Phenol",
    "cid": 996,
    "formula": "C6H6O",
    "mw": 94.11,
    "smiles": "C1=CC=C(C=C1)O",
    "iupac": "phenol",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "acetaldehyde",
    "name": "Acetaldehyde",
    "cid": 177,
    "formula": "C2H4O",
    "mw": 44.05,
    "smiles": "CC=O",
    "iupac": "acetaldehyde",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "acetone",
    "name": "Acetone",
    "cid": 180,
    "formula": "C3H6O",
    "mw": 58.08,
    "smiles": "CC(=O)C",
    "iupac": "propan-2-one",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "propionic-acid",
    "name": "Propionic Acid",
    "cid": 1032,
    "formula": "C3H6O2",
    "mw": 74.08,
    "smiles": "CCC(=O)O",
    "iupac": "propanoic acid",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "ethyl-acetate",
    "name": "Ethyl Acetate",
    "cid": 8857,
    "formula": "C4H8O2",
    "mw": 88.11,
    "smiles": "CCOC(=O)C",
    "iupac": "ethyl acetate",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "acetamide",
    "name": "Acetamide",
    "cid": 178,
    "formula": "C2H5NO",
    "mw": 59.07,
    "smiles": "CC(=O)N",
    "iupac": "acetamide",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "diethyl-ether",
    "name": "Diethyl Ether",
    "cid": 3283,
    "formula": "C4H10O",
    "mw": 74.12,
    "smiles": "CCOCC",
    "iupac": "ethoxyethane",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "methylamine",
    "name": "Methylamine",
    "cid": 6329,
    "formula": "CH5N",
    "mw": 31.057,
    "smiles": "CN",
    "iupac": "methanamine",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "methyl-chloride",
    "name": "Methyl Chloride",
    "cid": 6327,
    "formula": "CH3Cl",
    "mw": 50.49,
    "smiles": "CCl",
    "iupac": "chloromethane",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "acetonitrile",
    "name": "Acetonitrile",
    "cid": 6342,
    "formula": "C2H3N",
    "mw": 41.05,
    "smiles": "CC#N",
    "iupac": "acetonitrile",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "nitrobenzene",
    "name": "Nitrobenzene",
    "cid": 7416,
    "formula": "C6H5NO2",
    "mw": 123.11,
    "smiles": "C1=CC=C(C=C1)[N+](=O)[O-]",
    "iupac": "nitrobenzene",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "ethanethiol",
    "name": "Ethanethiol",
    "cid": 6343,
    "formula": "C2H6S",
    "mw": 62.14,
    "smiles": "CCS",
    "iupac": "ethanethiol",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "pyridine",
    "name": "Pyridine",
    "cid": 1049,
    "formula": "C5H5N",
    "mw": 79.1,
    "smiles": "C1=CC=NC=C1",
    "iupac": "pyridine",
    "categories": [
      "functional-groups"
    ],
    "mesh": []
  },
  {
    "id": "glycine",
    "name": "Glycine",
    "cid": 750,
    "formula": "C2H5NO2",
    "mw": 75.07,
    "smiles": "C(C(=O)O)N",
    "iupac": "2-aminoacetic acid",
    "categories": [
      "amino-acids"
    ],
    "mesh": []
  },
  {
    "id": "l-alanine",
    "name": "L-Alanine",
    "cid": 5950,
    "formula": "C3H7NO2",
    "mw": 89.09,
    "smiles": "C[C@@H](C(=O)O)N",
    "iupac": "(2S)-2-aminopropanoic acid",
    "categories": [
      "amino-acids"
    ],
    "mesh": []
  },
  {
    "id": "l-serine",
    "name": "L-Serine",
    "cid": 5951,
    "formula": "C3H7NO3",
    "mw": 105.09,
    "smiles": "C([C@@H](C(=O)O)N)O",
    "iupac": "(2S)-2-amino-3-hydroxypropanoic acid",
    "categories": [
      "amino-acids"
    ],
    "mesh": []
  },
  {
    "id": "l-cysteine",
    "name": "L-(+)-Cysteine",
    "cid": 5862,
    "formula": "C3H7NO2S",
    "mw": 121.16,
    "smiles": "C([C@@H](C(=O)O)N)S",
    "iupac": "(2R)-2-amino-3-sulfanylpropanoic acid",
    "categories": [
      "amino-acids"
    ],
    "mesh": []
  },
  {
    "id": "l-phenylalanine",
    "name": "L-Phenylalanine",
    "cid": 6140,
    "formula": "C9H11NO2",
    "mw": 165.19,
    "smiles": "C1=CC=C(C=C1)C[C@@H](C(=O)O)N",
    "iupac": "(2S)-2-amino-3-phenylpropanoic acid",
    "categories": [
      "amino-acids"
    ],
    "mesh": []
  },
  {
    "id": "l-tyrosine",
    "name": "L-Tyrosine",
    "cid": 6057,
    "formula": "C9H11NO3",
    "mw": 181.19,
    "smiles": "C1=CC(=CC=C1C[C@@H](C(=O)O)N)O",
    "iupac": "(2S)-2-amino-3-(4-hydroxyphenyl)propanoic acid",
    "categories": [
      "amino-acids"
    ],
    "mesh": []
  },
  {
    "id": "l-tryptophan",
    "name": "L-Tryptophan",
    "cid": 6305,
    "formula": "C11H12N2O2",
    "mw": 204.22,
    "smiles": "C1=CC=C2C(=C1)C(=CN2)C[C@@H](C(=O)O)N",
    "iupac": "(2S)-2-amino-3-(1H-indol-3-yl)propanoic acid",
    "categories": [
      "amino-acids"
    ],
    "mesh": []
  },
  {
    "id": "l-glutamic-acid",
    "name": "L-Glutamic Acid",
    "cid": 33032,
    "formula": "C5H9NO4",
    "mw": 147.13,
    "smiles": "C(CC(=O)O)[C@@H](C(=O)O)N",
    "iupac": "(2S)-2-aminopentanedioic acid",
    "categories": [
      "amino-acids"
    ],
    "mesh": []
  },
  {
    "id": "l-lysine",
    "name": "L-Lysine",
    "cid": 5962,
    "formula": "C6H14N2O2",
    "mw": 146.19,
    "smiles": "C(CCN)C[C@@H](C(=O)O)N",
    "iupac": "(2S)-2,6-diaminohexanoic acid",
    "categories": [
      "amino-acids"
    ],
    "mesh": []
  },
  {
    "id": "glucose",
    "name": "Glucose",
    "cid": 5793,
    "formula": "C6H12O6",
    "mw": 180.16,
    "smiles": "C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)O",
    "iupac": "(3R,4S,5S,6R)-6-(hydroxymethyl)oxane-2,3,4,5-tetrol",
    "categories": [
      "carbohydrates"
    ],
    "mesh": []
  },
  {
    "id": "fructose",
    "name": "Fructose",
    "cid": 2723872,
    "formula": "C6H12O6",
    "mw": 180.16,
    "smiles": "C1[C@H]([C@H]([C@@H](C(O1)(CO)O)O)O)O",
    "iupac": "(3S,4R,5R)-2-(hydroxymethyl)oxane-2,3,4,5-tetrol",
    "categories": [
      "carbohydrates"
    ],
    "mesh": []
  },
  {
    "id": "galactose",
    "name": "Galactose",
    "cid": 6036,
    "formula": "C6H12O6",
    "mw": 180.16,
    "smiles": "C([C@@H]1[C@@H]([C@@H]([C@H](C(O1)O)O)O)O)O",
    "iupac": "(3R,4S,5R,6R)-6-(hydroxymethyl)oxane-2,3,4,5-tetrol",
    "categories": [
      "carbohydrates"
    ],
    "mesh": []
  },
  {
    "id": "ribose",
    "name": "Ribose",
    "cid": 10975657,
    "formula": "C5H10O5",
    "mw": 150.13,
    "smiles": "C1[C@H]([C@H]([C@H](C(O1)O)O)O)O",
    "iupac": "(3R,4R,5R)-oxane-2,3,4,5-tetrol",
    "categories": [
      "carbohydrates"
    ],
    "mesh": []
  },
  {
    "id": "sucrose",
    "name": "Sucrose",
    "cid": 5988,
    "formula": "C12H22O11",
    "mw": 342.3,
    "smiles": "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@]2([C@H]([C@@H]([C@H](O2)CO)O)O)CO)O)O)O)O",
    "iupac": "(2R,3R,4S,5S,6R)-2-[(2S,3S,4S,5R)-3,4-dihydroxy-2,5-bis(hydroxymethyl)oxolan-2-yl]oxy-6-(hydroxymethyl)oxane-3,4,5-triol",
    "categories": [
      "carbohydrates"
    ],
    "mesh": []
  },
  {
    "id": "beta-lactose",
    "name": "Beta-Lactose",
    "cid": 6134,
    "formula": "C12H22O11",
    "mw": 342.3,
    "smiles": "C([C@@H]1[C@@H]([C@@H]([C@H]([C@@H](O1)O[C@@H]2[C@H](O[C@H]([C@@H]([C@H]2O)O)O)CO)O)O)O)O",
    "iupac": "(2R,3R,4S,5R,6S)-2-(hydroxymethyl)-6-[(2R,3S,4R,5R,6R)-4,5,6-trihydroxy-2-(hydroxymethyl)oxan-3-yl]oxyoxane-3,4,5-triol",
    "categories": [
      "carbohydrates"
    ],
    "mesh": []
  },
  {
    "id": "aspirin",
    "name": "Aspirin",
    "cid": 2244,
    "formula": "C9H8O4",
    "mw": 180.16,
    "smiles": "CC(=O)OC1=CC=CC=C1C(=O)O",
    "iupac": "2-acetyloxybenzoic acid",
    "categories": [
      "pharmaceutical",
      "cardiovascular"
    ],
    "mesh": [
      "Anti-Inflammatory Agents, Non-Steroidal",
      "Antipyretics",
      "Cyclooxygenase Inhibitors",
      "Fibrinolytic Agents",
      "Platelet Aggregation Inhibitors"
    ]
  },
  {
    "id": "salicylic-acid",
    "name": "Salicylic Acid",
    "cid": 338,
    "formula": "C7H6O3",
    "mw": 138.12,
    "smiles": "C1=CC=C(C(=C1)C(=O)O)O",
    "iupac": "2-hydroxybenzoic acid",
    "categories": [
      "pharmaceutical"
    ],
    "mesh": [
      "Anti-Infective Agents",
      "Antifungal Agents",
      "Keratolytic Agents"
    ]
  },
  {
    "id": "paracetamol",
    "name": "Paracetamol",
    "cid": 1983,
    "formula": "C8H9NO2",
    "mw": 151.16,
    "smiles": "CC(=O)NC1=CC=C(C=C1)O",
    "iupac": "N-(4-hydroxyphenyl)acetamide",
    "categories": [
      "pharmaceutical",
      "analgesics"
    ],
    "mesh": [
      "Analgesics, Non-Narcotic",
      "Antipyretics"
    ]
  },
  {
    "id": "ibuprofen",
    "name": "Ibuprofen, (+-)-",
    "cid": 3672,
    "formula": "C13H18O2",
    "mw": 206.28,
    "smiles": "CC(C)CC1=CC=C(C=C1)C(C)C(=O)O",
    "iupac": "2-[4-(2-methylpropyl)phenyl]propanoic acid",
    "categories": [
      "pharmaceutical",
      "analgesics"
    ],
    "mesh": [
      "Analgesics, Non-Narcotic",
      "Anti-Inflammatory Agents, Non-Steroidal",
      "Cyclooxygenase Inhibitors"
    ]
  },
  {
    "id": "naproxen",
    "name": "Naproxen",
    "cid": 156391,
    "formula": "C14H14O3",
    "mw": 230.26,
    "smiles": "C[C@@H](C1=CC2=C(C=C1)C=C(C=C2)OC)C(=O)O",
    "iupac": "(2S)-2-(6-methoxynaphthalen-2-yl)propanoic acid",
    "categories": [
      "pharmaceutical"
    ],
    "mesh": [
      "Anti-Inflammatory Agents, Non-Steroidal",
      "Cyclooxygenase Inhibitors",
      "Gout Suppressants"
    ]
  },
  {
    "id": "diclofenac",
    "name": "Diclofenac",
    "cid": 3033,
    "formula": "C14H11Cl2NO2",
    "mw": 296.1,
    "smiles": "C1=CC=C(C(=C1)CC(=O)O)NC2=C(C=CC=C2Cl)Cl",
    "iupac": "2-[2-(2,6-dichloroanilino)phenyl]acetic acid",
    "categories": [
      "pharmaceutical"
    ],
    "mesh": [
      "Anti-Inflammatory Agents, Non-Steroidal",
      "Cyclooxygenase Inhibitors"
    ]
  },
  {
    "id": "morphine",
    "name": "Morphine",
    "cid": 5288826,
    "formula": "C17H19NO3",
    "mw": 285.34,
    "smiles": "CN1CC[C@]23[C@@H]4[C@H]1CC5=C2C(=C(C=C5)O)O[C@H]3[C@H](C=C4)O",
    "iupac": "(4R,4aR,7S,7aR,12bS)-3-methyl-2,4,4a,7,7a,13-hexahydro-1H-4,12-methanobenzofuro[3,2-e]isoquinoline-7,9-diol",
    "categories": [
      "pharmaceutical",
      "analgesics",
      "cns"
    ],
    "mesh": [
      "Analgesics, Opioid",
      "Narcotics"
    ]
  },
  {
    "id": "codeine",
    "name": "Codeine",
    "cid": 5284371,
    "formula": "C18H21NO3",
    "mw": 299.4,
    "smiles": "CN1CC[C@]23[C@@H]4[C@H]1CC5=C2C(=C(C=C5)OC)O[C@H]3[C@H](C=C4)O",
    "iupac": "(4R,4aR,7S,7aR,12bS)-9-methoxy-3-methyl-2,4,4a,7,7a,13-hexahydro-1H-4,12-methanobenzofuro[3,2-e]isoquinolin-7-ol",
    "categories": [
      "pharmaceutical",
      "analgesics",
      "cns"
    ],
    "mesh": [
      "Analgesics, Opioid",
      "Antitussive Agents",
      "Narcotics"
    ]
  },
  {
    "id": "tramadol",
    "name": "Tramadol",
    "cid": 33741,
    "formula": "C16H25NO2",
    "mw": 263.37,
    "smiles": "CN(C)C[C@H]1CCCC[C@@]1(C2=CC(=CC=C2)OC)O",
    "iupac": "cis-(1R,2R)-2-[(dimethylamino)methyl]-1-(3-methoxyphenyl)cyclohexan-1-ol",
    "categories": [
      "pharmaceutical",
      "analgesics",
      "cns"
    ],
    "mesh": [
      "Analgesics, Opioid",
      "Narcotics"
    ]
  },
  {
    "id": "caffeine",
    "name": "Caffeine",
    "cid": 2519,
    "formula": "C8H10N4O2",
    "mw": 194.19,
    "smiles": "CN1C=NC2=C1C(=O)N(C(=O)N2C)C",
    "iupac": "1,3,7-trimethylpurine-2,6-dione",
    "categories": [
      "pharmaceutical",
      "cns"
    ],
    "mesh": [
      "Central Nervous System Stimulants",
      "Phosphodiesterase Inhibitors",
      "Purinergic P1 Receptor Antagonists"
    ]
  },
  {
    "id": "benzylpenicillin-penicillin-g",
    "name": "Benzylpenicillin (penicillin G)",
    "cid": 5904,
    "formula": "C16H18N2O4S",
    "mw": 334.4,
    "smiles": "CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)CC3=CC=CC=C3)C(=O)O)C",
    "iupac": "(2S,5R,6R)-3,3-dimethyl-7-oxo-6-[(2-phenylacetyl)amino]-4-thia-1-azabicyclo[3.2.0]heptane-2-carboxylic acid",
    "categories": [
      "pharmaceutical",
      "antibiotics"
    ],
    "mesh": [
      "Anti-Bacterial Agents"
    ]
  },
  {
    "id": "amoxicillin",
    "name": "Amoxicillin",
    "cid": 33613,
    "formula": "C16H19N3O5S",
    "mw": 365.4,
    "smiles": "CC1([C@@H](N2[C@H](S1)[C@@H](C2=O)NC(=O)[C@@H](C3=CC=C(C=C3)O)N)C(=O)O)C",
    "iupac": "(2S,5R,6R)-6-[[(2R)-2-amino-2-(4-hydroxyphenyl)acetyl]amino]-3,3-dimethyl-7-oxo-4-thia-1-azabicyclo[3.2.0]heptane-2-carboxylic acid",
    "categories": [
      "pharmaceutical",
      "antibiotics"
    ],
    "mesh": [
      "Anti-Bacterial Agents"
    ]
  },
  {
    "id": "ciprofloxacin",
    "name": "Ciprofloxacin",
    "cid": 2764,
    "formula": "C17H18FN3O3",
    "mw": 331.34,
    "smiles": "C1CC1N2C=C(C(=O)C3=CC(=C(C=C32)N4CCNCC4)F)C(=O)O",
    "iupac": "1-cyclopropyl-6-fluoro-4-oxo-7-piperazin-1-ylquinoline-3-carboxylic acid",
    "categories": [
      "pharmaceutical",
      "antibiotics"
    ],
    "mesh": [
      "Anti-Bacterial Agents",
      "Cytochrome P-450 CYP1A2 Inhibitors",
      "Topoisomerase II Inhibitors"
    ]
  },
  {
    "id": "sulfamethoxazole",
    "name": "Sulfamethoxazole",
    "cid": 5329,
    "formula": "C10H11N3O3S",
    "mw": 253.28,
    "smiles": "CC1=CC(=NO1)NS(=O)(=O)C2=CC=C(C=C2)N",
    "iupac": "4-amino-N-(5-methyl-1,2-oxazol-3-yl)benzenesulfonamide",
    "categories": [
      "pharmaceutical"
    ],
    "mesh": [
      "Anti-Infective Agents"
    ]
  },
  {
    "id": "chloramphenicol",
    "name": "Chloramphenicol",
    "cid": 5959,
    "formula": "C11H12Cl2N2O5",
    "mw": 323.13,
    "smiles": "C1=CC(=CC=C1[C@H]([C@@H](CO)NC(=O)C(Cl)Cl)O)[N+](=O)[O-]",
    "iupac": "2,2-dichloro-N-[(1R,2R)-1,3-dihydroxy-1-(4-nitrophenyl)propan-2-yl]acetamide",
    "categories": [
      "pharmaceutical",
      "antibiotics"
    ],
    "mesh": [
      "Anti-Bacterial Agents",
      "Protein Synthesis Inhibitors"
    ]
  },
  {
    "id": "metronidazole",
    "name": "Metronidazole",
    "cid": 4173,
    "formula": "C6H9N3O3",
    "mw": 171.15,
    "smiles": "CC1=NC=C(N1CCO)[N+](=O)[O-]",
    "iupac": "2-(2-methyl-5-nitroimidazol-1-yl)ethanol",
    "categories": [
      "pharmaceutical",
      "antibiotics"
    ],
    "mesh": [
      "Anti-Bacterial Agents",
      "Anti-Infective Agents",
      "Antiprotozoal Agents"
    ]
  },
  {
    "id": "tetracycline",
    "name": "Tetracycline",
    "cid": 54675776,
    "formula": "C22H24N2O8",
    "mw": 444.4,
    "smiles": "C[C@@]1([C@H]2C[C@H]3[C@@H](C(=O)C(=C([C@]3(C(=O)C2=C(C4=C1C=CC=C4O)O)O)O)C(=O)N)N(C)C)O",
    "iupac": "(4S,4aS,5aS,6S,12aR)-4-(dimethylamino)-1,6,10,11,12a-pentahydroxy-6-methyl-3,12-dioxo-4,4a,5,5a-tetrahydrotetracene-2-carboxamide",
    "categories": [
      "other"
    ],
    "mesh": []
  },
  {
    "id": "diphenhydramine",
    "name": "Diphenhydramine",
    "cid": 3100,
    "formula": "C17H21NO",
    "mw": 255.35,
    "smiles": "CN(C)CCOC(C1=CC=CC=C1)C2=CC=CC=C2",
    "iupac": "2-benzhydryloxy-N,N-dimethylethanamine",
    "categories": [
      "pharmaceutical",
      "antihistamines",
      "cns"
    ],
    "mesh": [
      "Anesthetics, Local",
      "Anti-Allergic Agents",
      "Antiemetics",
      "Histamine H1 Antagonists",
      "Hypnotics and Sedatives",
      "Sleep Aids, Pharmaceutical"
    ]
  },
  {
    "id": "chlorpheniramine",
    "name": "(+-)-Chlorpheniramine",
    "cid": 2725,
    "formula": "C16H19ClN2",
    "mw": 274.79,
    "smiles": "CN(C)CCC(C1=CC=C(C=C1)Cl)C2=CC=CC=N2",
    "iupac": "3-(4-chlorophenyl)-N,N-dimethyl-3-pyridin-2-ylpropan-1-amine",
    "categories": [
      "pharmaceutical",
      "antihistamines"
    ],
    "mesh": [
      "Anti-Allergic Agents",
      "Antipruritics",
      "Histamine H1 Antagonists"
    ]
  },
  {
    "id": "cetirizine",
    "name": "Cetirizine",
    "cid": 2678,
    "formula": "C21H25ClN2O3",
    "mw": 388.9,
    "smiles": "C1CN(CCN1CCOCC(=O)O)C(C2=CC=CC=C2)C3=CC=C(C=C3)Cl",
    "iupac": "2-[2-[4-[(4-chlorophenyl)-phenylmethyl]piperazin-1-yl]ethoxy]acetic acid",
    "categories": [
      "pharmaceutical",
      "antihistamines"
    ],
    "mesh": [
      "Anti-Allergic Agents",
      "Histamine H1 Antagonists, Non-Sedating"
    ]
  },
  {
    "id": "loratadine",
    "name": "Loratadine",
    "cid": 3957,
    "formula": "C22H23ClN2O2",
    "mw": 382.9,
    "smiles": "CCOC(=O)N1CCC(=C2C3=C(CCC4=C2N=CC=C4)C=C(C=C3)Cl)CC1",
    "iupac": "ethyl 4-(13-chloro-4-azatricyclo[9.4.0.03,8]pentadeca-1(11),3(8),4,6,12,14-hexaen-2-ylidene)piperidine-1-carboxylate",
    "categories": [
      "pharmaceutical",
      "antihistamines"
    ],
    "mesh": [
      "Anti-Allergic Agents",
      "Antipruritics",
      "Histamine H1 Antagonists, Non-Sedating"
    ]
  },
  {
    "id": "propranolol",
    "name": "Propranolol",
    "cid": 4946,
    "formula": "C16H21NO2",
    "mw": 259.34,
    "smiles": "CC(C)NCC(COC1=CC=CC2=CC=CC=C21)O",
    "iupac": "1-naphthalen-1-yloxy-3-(propan-2-ylamino)propan-2-ol",
    "categories": [
      "pharmaceutical",
      "cardiovascular"
    ],
    "mesh": [
      "Adrenergic beta-Antagonists",
      "Anti-Arrhythmia Agents",
      "Antihypertensive Agents",
      "Vasodilator Agents"
    ]
  },
  {
    "id": "atenolol",
    "name": "Atenolol",
    "cid": 2249,
    "formula": "C14H22N2O3",
    "mw": 266.34,
    "smiles": "CC(C)NCC(COC1=CC=C(C=C1)CC(=O)N)O",
    "iupac": "2-[4-[2-hydroxy-3-(propan-2-ylamino)propoxy]phenyl]acetamide",
    "categories": [
      "pharmaceutical",
      "cardiovascular"
    ],
    "mesh": [
      "Adrenergic beta-1 Receptor Antagonists",
      "Anti-Arrhythmia Agents",
      "Antihypertensive Agents",
      "Sympatholytics"
    ]
  },
  {
    "id": "amlodipine",
    "name": "Amlodipine",
    "cid": 2162,
    "formula": "C20H25ClN2O5",
    "mw": 408.9,
    "smiles": "CCOC(=O)C1=C(NC(=C(C1C2=CC=CC=C2Cl)C(=O)OC)C)COCCN",
    "iupac": "3-O-ethyl 5-O-methyl 2-(2-aminoethoxymethyl)-4-(2-chlorophenyl)-6-methyl-1,4-dihydropyridine-3,5-dicarboxylate",
    "categories": [
      "pharmaceutical",
      "cardiovascular"
    ],
    "mesh": [
      "Antihypertensive Agents",
      "Calcium Channel Blockers",
      "Vasodilator Agents"
    ]
  },
  {
    "id": "captopril",
    "name": "Captopril",
    "cid": 44093,
    "formula": "C9H15NO3S",
    "mw": 217.29,
    "smiles": "C[C@H](CS)C(=O)N1CCC[C@H]1C(=O)O",
    "iupac": "(2S)-1-[(2S)-2-methyl-3-sulfanylpropanoyl]pyrrolidine-2-carboxylic acid",
    "categories": [
      "pharmaceutical",
      "cardiovascular"
    ],
    "mesh": [
      "Angiotensin-Converting Enzyme Inhibitors",
      "Antihypertensive Agents"
    ]
  },
  {
    "id": "nifedipine",
    "name": "Nifedipine",
    "cid": 4485,
    "formula": "C17H18N2O6",
    "mw": 346.3,
    "smiles": "CC1=C(C(C(=C(N1)C)C(=O)OC)C2=CC=CC=C2[N+](=O)[O-])C(=O)OC",
    "iupac": "dimethyl 2,6-dimethyl-4-(2-nitrophenyl)-1,4-dihydropyridine-3,5-dicarboxylate",
    "categories": [
      "pharmaceutical",
      "cardiovascular"
    ],
    "mesh": [
      "Calcium Channel Blockers",
      "Tocolytic Agents",
      "Vasodilator Agents"
    ]
  },
  {
    "id": "furosemide",
    "name": "Furosemide",
    "cid": 3440,
    "formula": "C12H11ClN2O5S",
    "mw": 330.74,
    "smiles": "C1=COC(=C1)CNC2=CC(=C(C=C2C(=O)O)S(=O)(=O)N)Cl",
    "iupac": "4-chloro-2-(furan-2-ylmethylamino)-5-sulfamoylbenzoic acid",
    "categories": [
      "pharmaceutical",
      "cardiovascular"
    ],
    "mesh": [
      "Diuretics",
      "Sodium Potassium Chloride Symporter Inhibitors"
    ]
  },
  {
    "id": "hydrochlorothiazide",
    "name": "Hydrochlorothiazide",
    "cid": 3639,
    "formula": "C7H8ClN3O4S2",
    "mw": 297.7,
    "smiles": "C1NC2=CC(=C(C=C2S(=O)(=O)N1)S(=O)(=O)N)Cl",
    "iupac": "6-chloro-1,1-dioxo-3,4-dihydro-2H-1lambda6,2,4-benzothiadiazine-7-sulfonamide",
    "categories": [
      "pharmaceutical",
      "cardiovascular"
    ],
    "mesh": [
      "Antihypertensive Agents",
      "Diuretics",
      "Sodium Chloride Symporter Inhibitors"
    ]
  },
  {
    "id": "warfarin",
    "name": "Warfarin",
    "cid": 54678486,
    "formula": "C19H16O4",
    "mw": 308.3,
    "smiles": "CC(=O)CC(C1=CC=CC=C1)C2=C(C3=CC=CC=C3OC2=O)O",
    "iupac": "4-hydroxy-3-(3-oxo-1-phenylbutyl)chromen-2-one",
    "categories": [
      "pharmaceutical",
      "cardiovascular"
    ],
    "mesh": [
      "Anticoagulants",
      "Rodenticides"
    ]
  },
  {
    "id": "diazepam",
    "name": "Diazepam",
    "cid": 3016,
    "formula": "C16H13ClN2O",
    "mw": 284.74,
    "smiles": "CN1C(=O)CN=C(C2=C1C=CC(=C2)Cl)C3=CC=CC=C3",
    "iupac": "7-chloro-1-methyl-5-phenyl-3H-1,4-benzodiazepin-2-one",
    "categories": [
      "pharmaceutical",
      "cns"
    ],
    "mesh": [
      "Adjuvants, Anesthesia",
      "Anesthetics, Intravenous",
      "Anti-Anxiety Agents",
      "Anticonvulsants",
      "Antiemetics",
      "GABA Modulators",
      "Hypnotics and Sedatives",
      "Muscle Relaxants, Central"
    ]
  },
  {
    "id": "fluoxetine",
    "name": "Fluoxetine",
    "cid": 3386,
    "formula": "C17H18F3NO",
    "mw": 309.33,
    "smiles": "CNCCC(C1=CC=CC=C1)OC2=CC=C(C=C2)C(F)(F)F",
    "iupac": "N-methyl-3-phenyl-3-[4-(trifluoromethyl)phenoxy]propan-1-amine",
    "categories": [
      "pharmaceutical",
      "cns"
    ],
    "mesh": [
      "Antidepressive Agents, Second-Generation",
      "Cytochrome P-450 CYP2D6 Inhibitors",
      "Selective Serotonin Reuptake Inhibitors"
    ]
  },
  {
    "id": "chlorpromazine",
    "name": "Chlorpromazine",
    "cid": 2726,
    "formula": "C17H19ClN2S",
    "mw": 318.9,
    "smiles": "CN(C)CCCN1C2=CC=CC=C2SC3=C1C=C(C=C3)Cl",
    "iupac": "3-(2-chlorophenothiazin-10-yl)-N,N-dimethylpropan-1-amine",
    "categories": [
      "pharmaceutical",
      "cns"
    ],
    "mesh": [
      "Antiemetics",
      "Antipsychotic Agents",
      "Dopamine Antagonists"
    ]
  },
  {
    "id": "phenytoin",
    "name": "Phenytoin",
    "cid": 1775,
    "formula": "C15H12N2O2",
    "mw": 252.27,
    "smiles": "C1=CC=C(C=C1)C2(C(=O)NC(=O)N2)C3=CC=CC=C3",
    "iupac": "5,5-diphenylimidazolidine-2,4-dione",
    "categories": [
      "pharmaceutical",
      "cns"
    ],
    "mesh": [
      "Anticonvulsants",
      "Cytochrome P-450 CYP1A2 Inducers",
      "Voltage-Gated Sodium Channel Blockers"
    ]
  },
  {
    "id": "levodopa",
    "name": "Levodopa",
    "cid": 6047,
    "formula": "C9H11NO4",
    "mw": 197.19,
    "smiles": "C1=CC(=C(C=C1C[C@@H](C(=O)O)N)O)O",
    "iupac": "(2S)-2-amino-3-(3,4-dihydroxyphenyl)propanoic acid",
    "categories": [
      "pharmaceutical",
      "cns"
    ],
    "mesh": [
      "Antiparkinson Agents",
      "Dopamine Agents"
    ]
  },
  {
    "id": "metformin",
    "name": "Metformin",
    "cid": 4091,
    "formula": "C4H11N5",
    "mw": 129.16,
    "smiles": "CN(C)C(=N)N=C(N)N",
    "iupac": "3-(diaminomethylidene)-1,1-dimethylguanidine",
    "categories": [
      "pharmaceutical"
    ],
    "mesh": [
      "Hypoglycemic Agents"
    ]
  },
  {
    "id": "salbutamol",
    "name": "Salbutamol",
    "cid": 2083,
    "formula": "C13H21NO3",
    "mw": 239.31,
    "smiles": "CC(C)(C)NCC(C1=CC(=C(C=C1)O)CO)O",
    "iupac": "4-[2-(tert-butylamino)-1-hydroxyethyl]-2-(hydroxymethyl)phenol",
    "categories": [
      "pharmaceutical"
    ],
    "mesh": [
      "Adrenergic beta-2 Receptor Agonists",
      "Bronchodilator Agents",
      "Tocolytic Agents"
    ]
  },
  {
    "id": "omeprazole",
    "name": "Omeprazole",
    "cid": 4594,
    "formula": "C17H19N3O3S",
    "mw": 345.4,
    "smiles": "CC1=CN=C(C(=C1OC)C)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC",
    "iupac": "6-methoxy-2-[(4-methoxy-3,5-dimethyl-2-pyridinyl)methylsulfinyl]-1H-benzimidazole",
    "categories": [
      "pharmaceutical"
    ],
    "mesh": [
      "Anti-Ulcer Agents",
      "Proton Pump Inhibitors"
    ]
  },
  {
    "id": "lidocaine",
    "name": "Lidocaine",
    "cid": 3676,
    "formula": "C14H22N2O",
    "mw": 234.34,
    "smiles": "CCN(CC)CC(=O)NC1=C(C=CC=C1C)C",
    "iupac": "2-(diethylamino)-N-(2,6-dimethylphenyl)acetamide",
    "categories": [
      "pharmaceutical",
      "cardiovascular"
    ],
    "mesh": [
      "Anesthetics, Local",
      "Anti-Arrhythmia Agents",
      "Voltage-Gated Sodium Channel Blockers"
    ]
  },
  {
    "id": "npc209773",
    "name": "Npc209773",
    "cid": 174174,
    "formula": "C17H23NO3",
    "mw": 289.4,
    "smiles": "CN1[C@@H]2CC[C@H]1CC(C2)OC(=O)C(CO)C3=CC=CC=C3",
    "iupac": "[(1S,5R)-8-methyl-8-azabicyclo[3.2.1]octan-3-yl] 3-hydroxy-2-phenylpropanoate",
    "categories": [
      "other"
    ],
    "mesh": []
  },
  {
    "id": "nicotine",
    "name": "Nicotine",
    "cid": 89594,
    "formula": "C10H14N2",
    "mw": 162.23,
    "smiles": "CN1CCC[C@H]1C2=CN=CC=C2",
    "iupac": "3-[(2S)-1-methylpyrrolidin-2-yl]pyridine",
    "categories": [
      "pharmaceutical"
    ],
    "mesh": [
      "Ganglionic Stimulants",
      "Nicotinic Agonists",
      "Smoking Cessation Agents"
    ]
  },
  {
    "id": "dopamine",
    "name": "Dopamine",
    "cid": 681,
    "formula": "C8H11NO2",
    "mw": 153.18,
    "smiles": "C1=CC(=C(C=C1CCN)O)O",
    "iupac": "4-(2-aminoethyl)benzene-1,2-diol",
    "categories": [
      "pharmaceutical",
      "cardiovascular",
      "cns"
    ],
    "mesh": [
      "Cardiotonic Agents",
      "Dopamine Agents",
      "Sympathomimetics"
    ]
  },
  {
    "id": "histamine",
    "name": "Histamine",
    "cid": 774,
    "formula": "C5H9N3",
    "mw": 111.15,
    "smiles": "C1=C(NC=N1)CCN",
    "iupac": "2-(1H-imidazol-5-yl)ethanamine",
    "categories": [
      "pharmaceutical"
    ],
    "mesh": [
      "Histamine Agonists"
    ]
  },
  {
    "id": "serotonin",
    "name": "Serotonin",
    "cid": 5202,
    "formula": "C10H12N2O",
    "mw": 176.21,
    "smiles": "C1=CC2=C(C=C1O)C(=CN2)CCN",
    "iupac": "3-(2-aminoethyl)-1H-indol-5-ol",
    "categories": [
      "pharmaceutical"
    ],
    "mesh": [
      "Serotonin Receptor Agonists"
    ]
  }
];
