import { NextResponse } from "next/server";
import { revalidateTag } from "next/cache";
import { brRegisterLimiter, checkLimit } from "@/lib/rateLimit";
import { firstIssue, registrationSchema } from "@/lib/battle-royale/schemas";
import {
  SESSIONS_TAG,
  clientIpFrom,
  db,
  engineErrorResponse,
  errorResponse,
  readJson,
  readSettings,
} from "@/lib/battle-royale/server";
import { sendBattleEmail } from "@/lib/battle-royale/email";
import { formatEventDate, formatSlot } from "@/lib/battle-royale/format";
import type { RegistrationReceipt } from "@/lib/battle-royale/types";

/*
 * Public online registration. The Player ID and Game Code are generated by
 * Postgres (column defaults), never by the browser. The confirmation email is
 * best-effort: if Resend fails the registration stands, the failure is logged,
 * and an admin can resend it from the Emails page.
 */
export async function POST(req: Request) {
  const { success } = await checkLimit(brRegisterLimiter, clientIpFrom(req.headers));
  if (!success) return errorResponse("Too many registrations from this connection. Please try again in a few minutes.", 429);

  const parsed = registrationSchema.safeParse(await readJson(req));
  if (!parsed.success) return errorResponse(firstIssue(parsed.error), 400);
  const input = parsed.data;
  // A bot that filled the hidden field gets a success-shaped nothing.
  if (input.website) return NextResponse.json({ ok: true }, { status: 202 });

  const svc = await db();
  const { data: participant, error } = await svc.rpc("br_register", {
    p_name: input.name,
    p_email: input.email,
    p_phone: input.phone,
    p_university: input.university,
    p_year: input.pharmYear,
    p_student_id: input.studentId,
    p_slot_id: input.slotId ?? null,
    p_source: "online",
    p_payment_status: "unpaid",
  });
  if (error || !participant) return engineErrorResponse(error, "register");
  if (input.slotId) revalidateTag(SESSIONS_TAG);

  const [email, settings, slot] = await Promise.all([
    sendBattleEmail("registration", participant.id),
    readSettings(),
    input.slotId
      ? svc.from("br_sessions").select("name, start_time, end_time").eq("id", input.slotId).maybeSingle()
      : Promise.resolve({ data: null }),
  ]);

  const receipt: RegistrationReceipt = {
    name: participant.name,
    code: participant.participant_code,
    gameCode: participant.game_code,
    email: participant.email,
    slot: slot.data
      ? formatSlot({ name: slot.data.name, startTime: slot.data.start_time, endTime: slot.data.end_time })
      : null,
    eventDate: settings ? formatEventDate(settings.eventDate) : null,
    reportingTime: settings?.reportingTime ?? "",
    venue: settings?.venue ?? "",
    entryFee: settings?.entryFee ?? 100,
    emailStatus: email.status === "sent" ? "sent" : "failed",
  };
  return NextResponse.json({ ok: true, receipt }, { status: 201 });
}
